### ISSUE TITLE
Exclude map type from searching

### ISSUE THREAD

**Issue by Hawkz1994** [tm-rmc/MXRandom#52]
Hey Greep,

Would it be possible to add a multi-select dropdown to exclude map types from the search? For example when I don't want to play ICE and LOL, I would just add them to that dropdown and the plugin wouldn't load any map of that type.

Thanks for considering and keep up the good work.

**Comment by GreepTheSheep** [comment]
Hey @Hawkz1994, this is clearly possible! I'll add this asap

(query parameter `etags` to exclude tags)
