### ISSUE TITLE
"invalid webid" error on MP4

### ISSUE THREAD

**Issue by woutercools** [tm-rmc/MXRandom#54]
I get this message in the log in Maniaplanet

![2022-04-24 15_40_58-ManiaPlanet](https://user-images.githubusercontent.com/16439116/164979998-aa316120-8b96-44bc-8ddf-33d9780f1616.png)

https://trackmania.io/#/player/ab55cf14-bd86-4755-9e0d-2bef2d1cb59c

**Comment by woutercools** [comment]
I use a ManiaExchange Username to log into ManiaExchange, not my ManiaPlanet account.

![image](https://user-images.githubusercontent.com/16439116/164980246-cc82c64f-f3e6-4c4e-be11-18e1d9323065.png)

Maybe this is the cause?

**Comment by GreepTheSheep** [comment]
Nope, it's just I updated this only for TM2020 and forgot to add a check if we're on Maniaplanet
